spring.application.name=crud_basic
#url del servidor y base datos
#spring.datasource.url=jdbc:mysql://direccionip:puerto/DBname
spring.datasource.url=jdbc:mysql://localhost:3306/cinema
#user DB manager
spring.datasource.username=root
#password user db manager
spring.datasource.password=
#driver mysql
spring.datasource.driver-name=com.mysql.cj.jdbc.Driver
#update = verifica la base datos y actualiza la estructura
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080

server.address=0.0.0.0
